import React from 'react';
import './About.css';
import nowcast from './nowcast.gif';
import { NavLink } from 'react-router-dom';

function About() {
  document.body.classList.add('About');
  return (
    <div class='gif-container'>
      <h2>Generated Nowcast</h2>
      <div class='info'>
        A weather nowcast of a radar image indicates current weather conditions and near-term trends in a specific area. The radar image is generated by sending out radio waves that bounce off precipitation and other atmospheric particles, and the resulting image shows the intensity and location of the precipitation.

      A nowcast of a radar image can indicate the location and intensity of current precipitation, as well as the direction and speed of its movement. This information can be used to predict where and when the precipitation is likely to occur in the near future. Additionally, a nowcast can indicate the potential for severe weather, such as thunderstorms, tornadoes, or flash flooding, by highlighting areas of high precipitation intensity or rapidly changing weather conditions.
      </div>
      
   
      {<img src={nowcast} class='gif' />}

      <div className="button-grid">
        <button className="button">
          <NavLink to='/upload-page' activeClassName='active'>
            Uploaded GIF
          </NavLink>
        </button>
        <button className="button">
          <NavLink to='/gif-page' activeClassName='active'>
            Static GIF Frames
          </NavLink>
        </button>
        <button className="button">
          <NavLink to='/preprocessed-page' activeClassName='active'>
            Preprocessed Frames
          </NavLink>
        </button>
        <button className="button">
          <NavLink to='/precip-page' activeClassName='active'>
            Precipitation Frames
          </NavLink>
        </button>
        {/* <button className="button">
          <NavLink to='/precip-page' activeClassName='active'>
            Nowcast Frames
          </NavLink>
        </button> */}
      </div>

      {/* <button className='u-icon'>
        <NavLink to='/precip-page' activeClassName='active'>
          Precip
        </NavLink>
      </button> */}
    </div>
  );
}

export default About;
